---
- name: Obtener versiones de NCPA y del sistema operativo
  hosts: RHEL
  remote_user: root
  gather_facts: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Obtener la versión del sistema operativo
      ansible.builtin.debug:
        msg: "El sistema operativo es {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Verificar la familia del sistema operativo
      ansible.builtin.debug:
        msg: "Familia del sistema operativo: {{ ansible_os_family }}"

    - name: Obtener versión de NCPA en sistemas RHEL
      ansible.builtin.shell:
        cmd: "rpm -qi ncpa | grep Version | awk '{print $3}' | head -n 1"
      register: ncpa_version
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Obtener versión de NCPA en sistemas Ubuntu
      ansible.builtin.shell:
        cmd: "dpkg -s ncpa | grep Version | awk '{print $2}'"
      register: ncpa_version
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Mostrar la versión de NCPA
      ansible.builtin.debug:
        msg: "La versión de NCPA es: {{ ncpa_version.stdout }}"
      when: ncpa_version is defined and ncpa_version.stdout != ""
